### ISSUE TITLE
Idée : pouvoir définir le temps aléatoire

### ISSUE THREAD

**Issue by smuteau** [mika-nt28/Jeedom-Volets#16]
Par défaut c'est de 0 à 10s.
Serait-il possible d'avoir une case qui apparait lorsque l'on active "Présence" pour définir le temps que l'on veut (avec un maxi à 10mn par ex) ?

**Comment by mika-nt28** [comment]
Oui, c'est possible, je peux ajouté un champs de configuration
Ce sera toujours en seconde.
Pour l'instant j'ai fait simple afin de s'assurer que la fonction soit opérationnel

**Comment by mika-nt28** [comment]
La modification sera dans la prochaine mise a jours

**Comment by smuteau** [comment]
Impec merci :)
je teste dès que dispo
