### ISSUE TITLE
Problèmes sur gestion présence

### ISSUE THREAD

**Issue by unknownboy** [mika-nt28/Jeedom-Volets#168]
Bonjour @mika-nt28, 

Tout d'abord merci pour ton plugin.

Le bouton de suppression de la valeur de présence n'est pas fonctionnelle. Par contre, si l'on supprime la valeur dans le champ à coté et qu'on sauvegarde, ça le supprime bien.
![supprimerpresence](https://user-images.githubusercontent.com/2530749/31709078-366db360-b3f1-11e7-98c3-7c0327b4f7cd.jpg)

J'ai l'impression que sur ma version "2017-10-17 01:00:45", la vérification de présence s'exécute toujours même si je n'ai pas coché la case dans la page action "type de gestion" :
![presencedesactivee](https://user-images.githubusercontent.com/2530749/31709182-83166e32-b3f1-11e7-9906-db09e6fa618e.jpg)
Mes volets ne se sont pas ouverts ce matin ni hier probablement dû à ça. Je précise qu'historiquement j'avais une valeur dans le champ présence, mais pas de type de gestion présence et que mes volets s'ouvraient bien.

**Comment by mika-nt28** [comment]
Bonjour,

Effectivement le bouton - ne devrait pas etre la c'est un mauvais copier collé, d’ailleurs l’accès au action de scénario non plus.
J'ai corriger ce pour la prochaine release.
La gestion de présence ne s’exécute que lors d'un changement du  statut de l'objet.
Que disent les log est ce que tu en as qui traite de la présence?

**Comment by unknownboy** [comment]
Mes logs sont déjà effacés, mais ça indiquait effectivement que ça traitait la présence. J augmente l historique des logs et te renvoit un exemple.

**Comment by mika-nt28** [comment]
des news?
