### ISSUE TITLE
Visibilité du Temps Présence sans cocher la case Présence

### ISSUE THREAD

**Issue by smuteau** [mika-nt28/Jeedom-Volets#18]
L'option pour définir le Temps maximum pour le Présence est visible lors de la création d'une zone. Or la case Présence n'est pas cochée.
L'option disparait après avoir coché puis décoché la case Présence.

**Comment by smuteau** [comment]
D'après ton code (volets.js de desktop/js): 
$('body').on('change','.eqLogicAttr[data-l1key=configuration][data-l2key=isRandom]',function()...
il faudrait ajouter un 'create' en plus du 'change' (mais je ne m'y connais pas du tout alors je te laisse faire ;)

**Comment by mika-nt28** [comment]
Il n’existe pas ce genre d'event, du moins je ne le connais pas.
J'ai ajouté un masquage par défaut de ce champs.
Ce sera sur la prochaine release
