### ISSUE TITLE
Idée - inter-saison

### ISSUE THREAD

**Issue by altair2010** [mika-nt28/Jeedom-Volets#192]
Super travail. Ce plugin simplifie quand même bien les scénarios.

Serai-il possible d'ajouter la gestion des volets en inter-saison (Ajout de mode "printemps" et "automne" ?).
En effet c'est très pratique de ne pas avoir trop de soleil en été ou de conserver la chaleur en hiver, mais au printemps ou en automne, il manque de pouvoir garder de la luminosité le matin ou le soir.

Actuellement avec mes scénarios, je peux ouvrir plus tard au printemps car les matins son froid, et laisser un peu plus longtemps ouvert le soir.

En automne, j'ouvre avec le soleil, et je ferme avec lui, car le temps et souvent gris.

**Comment by mika-nt28** [comment]
On peut deja faire ca avec les delais au levé et couche du soleil
