### ISSUE TITLE
[Amélioration] AJout d'une commande % ouverture

### ISSUE THREAD

**Issue by Ikes72000** [mika-nt28/Jeedom-Volets#200]
Serait-il possible d'ajouter dans les commandes une commande % d'ouverture, sur le même principe que les commandes d'ouverture / fermeture actuelles?
On pourrait ainsi directement envoyer le pourcentage d'ouverture désiré à ton nouveau plugin (voletProp) en fonction des conditions sélectionnées.
Exemples:
- ouvrir 5% -> été -> héliotrope (ouvrir le volet à 5% l'été lorsque le soleil est dans la fenêtre)
- ouvrir 0% -> été & hiver -> nuit (fermer le volet l'été et l'hiver en mode nuit)

**Comment by mika-nt28** [comment]
La commande proportionnel peut être saisi dans les action.

Le plugin voletProp permet justement de pouvoir sélectionné une commande proportionnel du volet
