### ISSUE TITLE
Idée - Gestion des horaires à l'ouverture et à la fermeture.

### ISSUE THREAD

**Issue by noBru77** [mika-nt28/Jeedom-Volets#21]
Supprimer les champs des délais de l'onglet 'General'.
Garder les deux choix pour le 'Type de gestion du groupe'.

Si Choix 'Jour/Nuit': alors la configuration des horaires se fera dans chaque onglet 'Actions...'.

Sur les onglets 'Actions...':
- Définir une condition d'exécution des actions (précédent Issue).
- Définir soit un décalage par rapport au levée du soleil (ou couché suivant l'onglet Actions), soit une heure fixe des actions, soit une limite 'pas avant' si levée du soleil tôt pour l'ouverture et 'pas après' si couché du soleil tard pour la fermeture.

**Comment by mika-nt28** [comment]
Dans la dernière Release
 - Rassemblement des gestions
 - Choix d'application des conditions en fonction du type de gestion
 -
