### ISSUE TITLE
Bug - Cron non créé en mode Jour/Nuit si plusieurs zones.

### ISSUE THREAD

**Issue by noBru77** [mika-nt28/Jeedom-Volets#22]
Si plusieurs zones sont définies de type 'Jour/Nuit', et si une des zones indique une durée de délais dans l'onglet Général de la zone, alors les Actions d'ouverture s'exécutent tous en même temps, suivant l'heure calculée de la zone le plus tôt et de même pour les Actions de fermetures.

**Comment by mika-nt28** [comment]
Effectivement c'est un bug connue.
En jours nuit le plugin écrasait le cron précèdent. on exécutait donc la totalité des action a l'heure du dernier équipement configurer

Je parle au passé car j"ai corriger ca hier sur la dernière beta

**Comment by noBru77** [comment]
Je vais mettre à jour et tester ça demain.

**Comment by noBru77** [comment]
J'ai mis un titre plus explicite.

**Comment by mika-nt28** [comment]
C'est corrigé ca dans la derniere version
