### ISSUE TITLE
Bug - Cron et Suppression de Zones et/ou Plugin

### ISSUE THREAD

**Issue by noBru77** [mika-nt28/Jeedom-Volets#24]
Le plugin crée bien les 2 tâches cron pour chaque zone de type Jour/Nuit.

La suppression d'une zone ne supprime pas les tâches Cron correspondantes.

La désactivation ou la suppression du plugin ne désactive ou supprime pas toutes les tâches Cron volet.

Il faut utiliser la suppression en manuel, une fois le plugin supprimé.

**Comment by mika-nt28** [comment]
Effectivement c'est un oublie.
C'est ajouté
