### ISSUE TITLE
Horaires ouverture minimum et fermeture maximum: possibilité de mettre une expression

### ISSUE THREAD

**Issue by superbricolo** [mika-nt28/Jeedom-Volets#249]
Est ce que l'heure d'ouverture minimum ne pourrait pas être une expression. J'ai essayé, mais cela ne fonctionne pas. Cela éviterait de mettre une condition. Et comme en fonction des jours je n'ouvre pas toujours les volets à la même heure. Je voudrais mettre un expression du style:
min(time_op(variable(HeureOuvVolet,0730),60),1030)

Enfin si cela te paraît être une bonne idée.

Cordialement
Superbricolo

**Comment by mika-nt28** [comment]
C'est ajouté sur la beta
