### ISSUE TITLE
Bug - Statut Daemon NOK / Bouton Démarrer

### ISSUE THREAD

**Issue by noBru77** [mika-nt28/Jeedom-Volets#25]
J'ai réinstallé à neuf le Plugin suite à une nouvelle version et le bur sur les tâches cron, v2017-01-14 01:05:29
J'ai créé mes 3 zones.
Le statut du Daemon passe ne NOK une fois les zones activées.
Un Click sur le bouton Démarrer donne un message dans bandeau du haut en vert = Sauvegarde effectuée.
Pas de bouton 'Sauvegarder' sur la config du Plugin, je ne sais plus si c'est normal.

La seule manière d'avoir le status OK est de désactiver toutes les zones.

L'activation d'une des 3 zones force le plugin en status NOK.

Par contre les tâches Cron sont bien créées.

**Comment by mika-nt28** [comment]
Oui je me suis rendu compte qu'en voulant corrigé un bug j'en ai introduit un autre.
Je suis entrain de corriger

**Comment by noBru77** [comment]
Cool. Merci.

**Comment by mika-nt28** [comment]
C'est corrigé dans la derniere version
