### ISSUE TITLE
Pb heure ouverture mini et fermeture maxi

### ISSUE THREAD

**Issue by Gis70** [mika-nt28/Jeedom-Volets#253]
Bonjour,

L'heure d'ouverture mini n'est pas respectée si l'on a renseigné un délai.
Idem pour l'heure de fermeture.

Ce qu'il se passe c'est que ce délai est additionné ou soustrait à l'heure mini d'ouverture ou maxi de fermeture alors qu'elle devrait être bornée par cette valeur mini ou maxi.

**Comment by mika-nt28** [comment]
La correction est publier.
Elle sera disponible demain après réplication du github par le market
