### ISSUE TITLE
Ajout de templates de base

### ISSUE THREAD

**Issue by mika-nt28** [mika-nt28/Jeedom-Volets#258]
Bonjour a tous,

Je me demande s'il serait pas intéressante pour les futures utilisateur du plugin d'avoir la possibilité d'utilisé des Template de configuration prédéfini.
Ceci permettra d'avoir rapidement les fonction que l'on veux a personnaliser par la suite.

Pour ceux qui utilise le plugin EIBD / KNX ils connaissent le principe que j'ai mis en place et qui facilite l’intégration.

Quand pensez vous?
Quel Template pensez vous indispensable?

**Comment by ihexley** [comment]
Ok pour les Templates. Bien que je ne vois pas encore tous les avantages dans mon cas. Merci.

**Comment by mika-nt28** [comment]
Bah j'ai commencé a l’intégration et j'ai quand même un doute.
On verra si on le garde ou pas.

**Comment by ihexley** [comment]
Ok a tester donc.

**Comment by Rominous** [comment]
Bonjour, J'avoue que pour quelqu'un qui ne veut pas trop se casser la tête, avoir un "truc tout prêt" type modèle à pré-sélectionner serait top ! Voir laisser une possibilité de dupliquer son propre modèle (paramètres) sur l'objet volet  de son choix au lieu de dupliquer le volet directement (un peu sur la base des modules Zwave avec une conf recommandée...?)

**Comment by mika-nt28** [comment]
L'idée est la c'est d'avoir une configuration de base toute prêt.
Il n'y a que les paramétré propre a sa configuration a sélectionné.
Mais le problème que je vois en codant la fonction est qu'il y a encore beaucoup de paramètre a mettre a jours

La duplication d'une gestion a toujours été présente
