### ISSUE TITLE
Widget affichant un retour d'état du volet fermé alors que le log indique le contraire

### ISSUE THREAD

**Issue by Rominous** [mika-nt28/Jeedom-Volets#260]
Log : 
`[2018-05-25 09:55:06][INFO] : [Salon][Volet Meridienne] : Le plugin est configuré en mode été
[2018-05-25 09:55:06][INFO] : [Salon][Volet Meridienne][Gestion Azimut] : L'azimut 96° est compris entre : 194°  et 15° => Faux
[2018-05-25 09:55:06][INFO] : [Salon][Volet Meridienne][Gestion Azimut] : Le soleil n'est pas dans la fenêtre
[2018-05-25 09:55:06][INFO] : [Salon][Volet Meridienne][Gestion Azimut] : Les conditions sont remplies pour open
[2018-05-25 09:55:06][INFO] : [Salon][Volet Meridienne][Gestion Azimut] : Autorisation d'executer les actions
[2018-05-25 09:55:06][DEBUG] : [Salon][Volet Meridienne][Gestion Azimut] : Exécution de #[Salon][ZW Volet Meridienne][Positionnement]# ({"slider":100})
[2018-05-25 09:55:07][INFO] : [Salon][Volet Meridienne] : Changement de l'état réel du volet
[2018-05-25 09:55:07][DEBUG] : [Salon][Volet Meridienne] : 99 >= 0 => open`

Cela ne semble pas avoir d'impact sur a gestion en elle-même mais visuellement sur le dashbord c'est pas évident !
Me redire si ce log ne convient pas.
PS avant de passer en BETA cela fonctionnait.

Un beau dessin vaut parfois mieux qu'une grande explication : En espérant que l'image soit assez claire. En gros sur cette vue la position réelle des volets en bas via les retour d'état FIBARO et au dessus les différentes gestions et leurs retour d'état. La position des volets fibaro est correcte par rapport aux demandes du plugin (Il fait pas très chaud actuellement alors les volets restent ouverts !) Il reste donc les restour d'état widget pas très cohérents dont ci-dessus le log pour la méridienne.
![image](https://user-images.githubusercontent.com/39592696/40533472-395e2546-6003-11e8-971d-66dd0b799518.png)

**Comment by mika-nt28** [comment]
Je ne comprend pas ton probleme
Ton log indique 
Changement de l'état réel du volet [2018-05-25 09:55:07][DEBUG] : [Salon][Volet Meridienne] : 99 >= 0 => open
Et sur le widget [Volet Meridienne] elle est bien affiche en open

**Comment by Rominous** [comment]
Ah oui en effet, sur ce screenshot j'avais du changer manuellement le retour d'état pour la méridienne. Sur cet exemple visuel, (à log identiques) on constate l'anomalie sur Chambre ami et Chambre BB...

**Comment by mika-nt28** [comment]
C'est peut être un problème de widget, il y a eu de changement sur la derniere version de jeedom et je ne sais pas si j'ai bien tout mis a jours.
Si tu test la commande que te renvoie t'elle?

**Comment by mika-nt28** [comment]
L'autre point qui peut empêcher la mise a jours de l’état, c'est l'acquittement de l’état qui vient d’être mise en place.
Si tu utilise des commande proportionnel la valeur d'acquittement sera celle saisi sinon le plugin attend 0 pour fermer et 100 pour ouvert.
C'est un point qu'il faut que j'améliore car ce n'est pas toujours le cas

**Comment by Rominous** [comment]
Toutes mes excuses pour les délais de réponse (j'ai un boulot très prenant !), il semblerait en effet que le seuil abaissé à 98 permet au plugin de considérer les volets gérés par des FIBARO comme ouverts.

J'ai cependant toujours cette anomalie entre l'état réel du volet et le retour d'état du widget : erreur qui ne me semble pas si anodine car en actualisant le retour d'état du widget en corrélation avec l'état réel, cela relance parfois la gestion du volet. (le plugin croyant que le volet était auparavant dans la bonne position)

**Comment by mika-nt28** [comment]
Justement la dernière mise a jours met a jours l’état a chaque itération du retour d’état reel.
On attend plus l'acquittement pour mettre jours.

Quel est la version que tu utilise actuellement?

**Comment by Rominous** [comment]
Version : market / plugin : Volets beta | 2018-05-29 02:11:19

Et en effet je n'avais pas vu la MaJ, je viens d'actualiser et je lance la nouvelle MaJ dès maintenant. Je regarderais ça demain matin si tout se fait normalement.
