### ISSUE TITLE
Ajout de l'altitude d'obstruction

### ISSUE THREAD

**Issue by mika-nt28** [mika-nt28/Jeedom-Volets#267]

**Comment by Rominous** [comment]
Bonjour,

Qu'est-ce ? Comment cela fonctionne ?

**Comment by mika-nt28** [comment]
En faite ce nouveau paramètre permet au ratioVertical de calculer sa auteur uniquement si le soleil est a un altitude supérieur a l'altitude d'obstruction.
C'est a dire tu es en bas d'une montagne et le soleil passe au dessus de la montagne a une altitude de 60°
Donc ton paramètre d'altitude d'obstruction sera 60

**Comment by Rominous** [comment]
Ok, super idée ! 
Altitude d'obstruction == Altitude mini du passage en mode AZIMUT ?
Donc on peut envisager utiliser cette commande pour par exemple faire ouvrir les volets quand le soleil est en dessous d'un niveau (ou derrière la montage) mais aussi quand il est en phase descendante et qu'il chauffe moins (profiter du coucher du soleil) ?

Par ailleurs, serai-il possible d'incrémenter la petite soeur ? : 
Altitude maxi (plafond) de sortie (ponctuelle ou pas) du mode AZIMUT ?
Servirait par exemple à prendre en compte les ombrages en partie haute donnant déjà de l'ombre de façon naturelle (arbre / casquette / préhaut) et permettant ainsi d'ouvrir les volets et faire rentrer la lumière ?

**Comment by mika-nt28** [comment]
Oui pourquoi pas

**Comment by Rominous** [comment]
Ok vu sur la MaJ par contre pour le côté pratique, indiquer devant le texte et pas dans le champ car le test est trop long et du coup on ne sait pas a quoi correspond la case ^^
Peut-être un truc comme ça : 
Altitude d'obstruction en titre : 
Ne pas ouvrir si soleil est en dessous de XXXX °
Ouvrir si le soleil passe au dessus de XXX °
(Pour une meilleure compréhension de tous.)
Peut-être prévoir quand on passe sur les point d'interrogation un complément d'exemples concrets ou d'explication pour la détermination de l'angle.

Pour avis.

**Comment by mika-nt28** [comment]
Je rajoute ca
