### ISSUE TITLE
Bug - désactivation d'une zone supprime les logs

### ISSUE THREAD

**Issue by smuteau** [mika-nt28/Jeedom-Volets#27]
Je viens de tester une zone et j'ai suivi le fonctionnement en Debug dans le log.
Dès que j'ai désactivé ma zone de test, le log s'est vidé.
De ce fait je ne peux plus récupérer l'historique de les tests (pour te les envoyer ...).

**Comment by noBru77** [comment]
Je confirme. Les Logs se vident dès une désactivation ou même, si je ne me trompe pas, une MAJ du Plugin.

**Comment by mika-nt28** [comment]
Lors d'une sauvegarde de la configuration le démon est redémarre et donc les log effacé.
C'est tout a fait normal.
Pourquoi vouloir desactivé la zone?

**Comment by smuteau** [comment]
J'ai désactivé la zone pour des tests, tout simplement.
C'est surtout que j'y ai mis 3 volets au lieu des messages pour tester, et ensuite j'ai désactivé plutôt que de supprimer.

**Comment by mika-nt28** [comment]
J'ai changer la methode pour la prochaine version.
Je cree directement a la sauvegarde les cron plutot que de relancer la gestion du demon
