### ISSUE TITLE
Rationalisation des commandes envoyées

### ISSUE THREAD

**Issue by Rominous** [mika-nt28/Jeedom-Volets#272]
Je met ici une su gestion qui n'est pas spécialement un bug mais une piste de rationalisation des commandes envoyées au volets : 
Deux cas rencontrés mais je suppose que c"est le cas sur toutes les gestions, j'entends (et après vérification sur les log je le vois aussi) claquer les relais des modules à chaque CRON alors que le volet est déjà dans la bonne position (ce que sait le plugin car il a retour d'état)

==> Serait-il donc possible d'effectuer une petite vérif avant d'envoyer une commande de type : 
SI Etat ou position du volet == Celle souhaitée ALORS on fait rien SINON on fait ce qu'il faut ?

Je doute que les relais soient prévu pour être actionnés toutes les XX minutes... (et leur durée de vie avec)

**Comment by mika-nt28** [comment]
Normalement c'est le cas chez moi il ne bouge pas

**Comment by Rominous** [comment]
Je ne dis pas que le volet bouge mais dans le fonctionnement intrinsèque d'un module de volet il y a une détection de la charge par ce dernier qui comprend que le volet est arrivé en haut ou en bas. Pour cela chaque module ouvre/ferme son relais interne pour envoyer un peu de jus dès qu'on lui demande de monter/descendre (que ce soit sur un bouton physique ou sur une commande Up ou Slider 100/99...).

Et comme le plugin (sur cette BETA actuellement, je ne me rappelle plus comme c'était avant) envoie une commande d'ouverture alors que c'est déjà ouvert à chaque CRON, le relais claque...
==> Je peux poser la question sur le forum pour savoir si d'autres sont concernés ?

**Comment by mika-nt28** [comment]
Le plugin emet un log pour chaque commande exécute.
Est ce que tu retrouve se log?

**Comment by Rominous** [comment]
Ça a l'air bon pour les répétitions

Le lun. 11 juin 2018 à 13:45, Halbout Michael <notifications@github.com> a
écrit :
