### ISSUE TITLE
Commande pour ratio vertical

### ISSUE THREAD

**Issue by Rominous** [mika-nt28/Jeedom-Volets#293]
Bonjour Mika,

Je me permets de revenir vers toi au sujet de cette proposition réalisée sur le forum et ayant expliqué l'intérêt de cette modification. Qu'en est-il ? as-tu essayé de l'incrémenter ? L'idée serait de pouvoir faire ça : 
![image](https://user-images.githubusercontent.com/39592696/41896604-517d58dc-7925-11e8-99a7-9760e60dcdad.png)
(Ce qui aujourd'hui ne semble pas fonctionner)

**Comment by mika-nt28** [comment]
C'est ajouté a la prochaine release

**Comment by Rominous** [comment]
Super Merci, je reviendrais vers toi avec d'autres explication et utilisations concrètes.
