### ISSUE TITLE
Erreur suite MAJ 3.2.10 jeedom

### ISSUE THREAD

**Issue by unknownboy** [mika-nt28/Jeedom-Volets#296]
Salut Mika, 

Depuis aujourd'hui (mise à jour 3.2.10), impossible de lancer le démon : 
500 : Internal Server Error 

Dans le log http, je vois : 
[Mon Jul 02 22:26:45.816642 2018] [:error] [pid 2143] [client 127.0.0.1:45104] PHP Fatal error:  Class 'Symfony\Component\ExpressionLanguage\Token' not found in /var/www/html/vendor/symfony/expression-language/Lexer.php on line 51

Si tu as besoin de plus d'information ou de tests, n'hésite pas.

Merci :)

**Comment by mika-nt28** [comment]
L'erreur est sur symfony je ne peux rien y faire
