### ISSUE TITLE
Evaluation de la reactivation Heliotrope en mode nuit

### ISSUE THREAD

**Issue by mika-nt28** [mika-nt28/Jeedom-Volets#349]
Rechercher se bug

**Comment by Naboleo** [comment]
A voir si les dernières optimisation (pas d'évaluations azimut/altitude en mode nuit) corrigent le problème.

**Comment by mika-nt28** [comment]
Je viens de verifie ce point
Le plugin Heliotrope met a jours ses valeur et je ne peux pas l'arreter.
Pour cela je fait juste un control sur le mode actif
`if (!$this->getConfiguration('Azimut')
	    || $Mode == "Nuit" 
	    || $Mode == "Evenement" 
	    || $Mode == "Conditionnel")
		return false;`
Donc en gros le plugin ne fait rien si un de ses gestions est la gestion active
Dans tes log tu vois l'evaluation des angle pour savoir si on doit ouvrir ou fermer mais on en tien pas compte par la suite

**Comment by Naboleo** [comment]
Le plugin Heliotrope envoi les données mais ta fonction "pull" permet a priori de filtrer les événements et donc les calculs  (c'est le sens de ma modif)

> 					case 'azimuth360':
> 						**if($Volet->getCmd(null,'gestion')->execCmd() != "Nuit"){**
> 							log::add('Volets','info',$Volet->getHumanName().' : Mise à jour de l\'azimut du soleil');	
> 							$Volet->GestionAzimute($_option['value']);
> 						}
> 					break;
> 					case 'altitude':
> 						

> if($Volet->getCmd(null,'gestion')->execCmd() != "Nuit"){

> 							log::add('Volets','info',$Volet->getHumanName().' : Mise à jour de l\'altitude du soleil');	
> 							$Volet->checkAltitude($_option['value']);
> 						}
> 					break;
