### ISSUE TITLE
Idée : OpenStreetMap

### ISSUE THREAD

**Issue by smuteau** [mika-nt28/Jeedom-Volets#35]
C'est possible d'utiliser les cartes d'OSM au lieu de googlemaps ?
Juste pour degoogleliser un peu plus et parce que l'open source et l'open data c'est bien :)

**Comment by mika-nt28** [comment]
Je ne connaissais pas cette librairie.
Je vais regarder comment elle fonction pour l'integration

**Comment by mika-nt28** [comment]
J'ai enfin fini l’intégration de openLayer.
Plus que quelque teste et je l'envoie sur le market
