### ISSUE TITLE
Idée : ouverture random

### ISSUE THREAD

**Issue by smuteau** [mika-nt28/Jeedom-Volets#4]
Salut mika,
j'ai une télécommande somfy qui permet de faire une ouverture des volets "au hasard" avec un délai entre chaque.
Ca permet aux volets de s'ouvrir un par un, comme si quelqu'un les ouvrait au fur-et-à-mesure.
Sur ma télécommande, la fonction s'appelle "Présence".
Je vois bien une case à cocher qui permet d'activer ou non cette fonctionnalité.
Qu'en penses-tu ? faisable ?

**Comment by mika-nt28** [comment]
C'est faisable, je vais réfléchir a la meilleur intégration possible

**Comment by mika-nt28** [comment]
J'ai mise a jours le plugin.
Il faut attendre la réplication du github pour pouvoir en profité et surtout tester
