### ISSUE TITLE
Verifier l'etat du volet avant d'envoyer la commande

### ISSUE THREAD

**Issue by oon59** [mika-nt28/Jeedom-Volets#41]
Bonjour ne pourrait on pas verifier que le volet est deja ouvert (ou ferme) ou si l'ordre a deja ete transmis pour ne pas l'envoyer toutes les 5 mn

Cordialement
Nicolas

**Comment by mika-nt28** [comment]
Normalement la correction est dans la mise a jours de ce matin.
Je me suis assuré que la mise a jours plantait pas jeedom mais je n'ai pas eu le temps de tester si elle corrigeait bien le défaut remonté
