### ISSUE TITLE
Lancer un scénario et/ou pose depuis les actions d'ouverture / fermeture?

### ISSUE THREAD

**Issue by StephaGau** [mika-nt28/Jeedom-Volets#49]
Suite à ta demande du 27/03/2017 sur le forum, j'ouvre une issue...
Peux tu essayer de programmer l'exécution des scénarios et/ou des pauses via les actions d'ouverture & fermeture?
Bon courage😉 et merci...

**Comment by mika-nt28** [comment]
J'ai ajouté cette demande sur la prochaine release.
Je n'ai pas trouvé le temps de tester son exécution, tien moi au courant si cela fonctionne

**Comment by StephaGau** [comment]
Merci de la rapidité et du travail fourni🤗🤗
J'essaie demain...
Je te ferais un retour!

**Comment by StephaGau** [comment]
Bonjour Mikaël,

Désolé d'insister, mais de mon côté çà ne fonctionne toujours pas ?!
Lorsque je sélectionne le 1er carré vert(celui de gauche), celui ci ne m'ouvre rien (aucune nouvelle fenêtre)...
Je ne peux donc toujours pas lancer de scénario et/ou faire une pause.
Voici l'erreur
 getResource.php?file=plugins/Volets/desktop/js/Volets.js&md5=e4300c1…&lang=…:466 Uncaught TypeError: jeedom.getSelectActionModal is not a function
    at HTMLAnchorElement.<anonymous> (getResource.php?file=plugins/Volets/desktop/js/Volets.js&md5=e4300c1…&lang=…:466)
    at HTMLBodyElement.dispatch (getResource.php?file=3rdparty/jquery/jquery.min.js&md5=b354cc9…&lang=fr_FR:3)
    at HTMLBodyElement.r.handle (getResource.php?file=3rdparty/jquery/jquery.min.js&md5=b354cc9…&lang=fr_FR:3)
@ ta disposition

**Comment by mika-nt28** [comment]
Étrange chez moi cela fonctionne et j'appelle un fonction du core de jeedom.
Est ce que tu as un autre plugin qui as cette fonctionnalité car je doute que cette erreur soit liée au plugin directement.
Néanmoins je vais regardé si je trouve quelque chose

**Comment by StephaGau** [comment]
Malheureusement je n'ai aucun autre Plugin avec cette fonctionnalité...
Par contre lorsque je vais dans les scénarios tout fonctionne!
@ ta disposition...

**Comment by mika-nt28** [comment]
Le plugin mode a cette option.

Je pense avoir trouvé le problème c'est que cette option est disponible sur la beta mais pas sur la stable.
Il faudra donc attendre la sortie de jeedom V3 pour avoir cette possibilité

**Comment by StephaGau** [comment]
Ok merci pour ces retours rapides...
@ +
