### ISSUE TITLE
Déterminer les angles ne se met pas à jour

### ISSUE THREAD

**Issue by BenBenJD** [mika-nt28/Jeedom-Volets#506]
Hello,

J'ai un bug depuis la MAJ 2019-05-27 09:17:27 (Version Jeedom3.2.8) : 

Lorsqu'on créé une zone et qu'on lui détermine les angles dans Azimut : no problem.

Par contre lorsqu'on veut mettre à jour les angles, on les modifie sur la carte, on ferme la fenêtre (il n'y a pas de valider), on sauvegarde la modification et les angles restent les mêmes.

D'ailleurs si ces valeurs pouvaient être paramétrable via le clavier ce serait top car des fois on aimerait bien ajuster au degré près le moment ou l'action doit être réalisé.

(beau travail sinon)

**Comment by mika-nt28** [comment]
Corrigé
