### ISSUE TITLE
Vérification de l'altitude d'obstruction n'a pas l'air de fonctionner

### ISSUE THREAD

**Issue by Noodlex** [mika-nt28/Jeedom-Volets#533]
J'ai définit une altitude d'obstruction min à 30 mais quand l'altitude du soleil est en dessous de 30, le volet ne se lève pas. Pourtant, d'après l'aide de cette option, il est bien stipulé que si l'altitude du soleil est en dessous de la valeur min ou au dessus de la valeur maximum, celui-ci ouvre le volet.

J'ai parcouru un peu le code et voici ce que j'ai remarqué, est-ce normal ? La vérification de l'altitude est en commentaire.
https://github.com/mika-nt28/Jeedom-Volets/blob/5224be1de7554a3ee864d0fd7d5053ee6a1de9c7/core/class/Volets.class.php#L486

**Comment by mika-nt28** [comment]
Je ne me souvient plus de pourquoi je l'ai mis en commantaire mais c'est certainement le probleme que tu rencontre

Faut que je fasse des teste pour voir ca car effectivement c'est un probleme

**Comment by mika-nt28** [comment]
Je l'ai reactivé sur la beta

**Comment by Noodlex** [comment]
De mon côté, à chaque mise à jour je l'ai réactivé et je n'ai pas vu de soucis.

**Comment by mika-nt28** [comment]
Ok je le pousse en stable
