### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Noodlex** [mika-nt28/Jeedom-Volets#534]
J'ai déjà finit une valeur minimal dans la partie commande au niveau de "l'état du volet", je ne veux pas qu'il se ferme totalement mais laisse un écart entre les latte, donc la valeur minimal est de 16 et non 0.

Cependant, le plugin envoie toujours la valeur de 0 et non de 16.

Est-ce que j'ai mal configuré le plugin ou mal compris ?

Si j'ai mal compris, je propose une nouvel action en plus de "été" et "hiver" qui serait "personnalisé" où on pourrait encoder la valeur min et max pour la position du volet à prendre en compte.

https://github.com/mika-nt28/Jeedom-Volets/blob/34d208327bddac6fe280758ec46db57282a51fca/core/class/Volets.class.php#L521

**Comment by mika-nt28** [comment]
Je ne comprend pas le probleme.
Les valeurs min et max des commande vont definir la plage de fonctionnement du volet.
Si tu fait une action up ou down le plugin ne control pas la hauteur et n'est pas en mesure de relaisé ce que tu souhaite
Par contre en action tu peux luis mettre une action proportionnel a 16 pour les gestion qui t'interresse

**Comment by Noodlex** [comment]
Oui, je vois mon erreur, merci
