### ISSUE TITLE
Entrée/sortie de gestion événementielle ne se passe pas toujours bien

### ISSUE THREAD

**Issue by BadWolf42** [mika-nt28/Jeedom-Volets#548]
De temps en temps l'évaluation de la condition n'aboutit pas à un changement de gestion :
> [2019-08-05 08:13:20][DEBUG] : [Bibliothèque][Volet Auto] : Le plugin est configuré en mode été
> [2019-08-05 08:13:27][INFO] : [Bibliothèque][Volet Auto]#3066# : Un evenement s'est produit sur un objet ecouté
> [2019-08-05 08:13:27][INFO] : [Bibliothèque][Volet Auto][Gestion Evenement] : Evaluation de la condition : [#[Appartement][Mode][Mode]#=="Empty"]["Empty"=="Empty"] = **Vrai**
> [2019-08-05 08:13:27][DEBUG] : [Bibliothèque][Volet Auto] : Le plugin est configuré en mode été
> [2019-08-05 08:13:27][DEBUG] : [Bibliothèque][Volet Auto] : Le plugin est configuré en mode été
> [2019-08-05 08:13:27][INFO] : [Bibliothèque][Volet Auto]#3066# : Un evenement s'est produit sur un objet ecouté
> [2019-08-05 08:13:27][INFO] : [Bibliothèque][Volet Auto][Gestion Evenement] : Evaluation de la condition : [#[Appartement][Mode][Mode]#=="Hibernate"]["Empty"=="Hibernate"] = Faux
> [2019-08-05 08:13:27][DEBUG] : [Bibliothèque][Volet Auto] : Le plugin est configuré en mode été

Mais des fois oui :
> [2019-08-05 08:13:33][INFO] : [Bibliothèque][Volet Auto][Gestion Jour] : Exécution de la gestion du lever du soleil
> [2019-08-05 08:13:33][DEBUG] : [Bibliothèque][Volet Auto] : Le plugin est configuré en mode été
> [2019-08-05 08:13:33][DEBUG] : [Bibliothèque][Volet Auto] : Le plugin est configuré en mode été
> [2019-08-05 08:13:33][INFO] : [Bibliothèque][Volet Auto][Gestion Evenement] : Evaluation de la condition : [#[Appartement][Mode][Mode]#=="Empty"]["Empty"=="Empty"] = **Vrai**
> [2019-08-05 08:13:33][INFO] : [Bibliothèque][Volet Auto][Gestion Jour] : **Une condition évenementielle est valide, nous exécutons la gestion Evenement**
> [2019-08-05 08:13:33][DEBUG] : [Bibliothèque][Volet Auto][Gestion Empty] : Position actuelle = 100
> [2019-08-05 08:13:33][DEBUG] : [Bibliothèque][Volet Auto][Gestion Empty] : Position demandée = 25
> [2019-08-05 08:13:33][DEBUG] : [Bibliothèque][Volet Auto][Gestion Empty] : **Exécution de #[Bibliothèque][Volet][Position]# ({"slider":75})**
> [2019-08-05 08:13:40][INFO] : [Bibliothèque][Volet Auto][Etat] : Changement de l'état réel du volet => 25%
> [2019-08-05 08:13:40][DEBUG] : [Bibliothèque][Volet Auto][Etat] : Le changement d'état est autorisé

Certaines fois la sortie ne se passe pas bien non plus :
> [2019-08-05 17:40:28][INFO] : [Bibliothèque][Volet Auto]#3066# : Un evenement s'est produit sur un objet ecouté
> [2019-08-05 17:40:28][INFO] : [Bibliothèque][Volet Auto][Gestion Evenement] : Evaluation de la condition : [#[Appartement][Mode][Mode]#=="Empty"]["Alive"=="Empty"] = Faux
> [2019-08-05 17:40:28][INFO] : [Bibliothèque][Volet Auto]#3066# : Un evenement s'est produit sur un objet ecouté
> [2019-08-05 17:40:28][INFO] : [Bibliothèque][Volet Auto][Gestion Evenement] : Evaluation de la condition : [#[Appartement][Mode][Mode]#=="Hibernate"]["Alive"=="Hibernate"] = Faux

Ici j'ai finalement bougé le volet moi-même :
> [2019-08-05 20:26:17][INFO] : [Bibliothèque][Volet Auto][Etat] : Changement de l'état réel du volet => 100%
> [2019-08-05 20:26:17][DEBUG] : [Bibliothèque][Volet Auto][Etat] : Le changement d'état n'est pas autorisé
> [2019-08-05 20:26:18][DEBUG] : [Bibliothèque][Volet Auto] : Le plugin est configuré en mode été
> [2019-08-05 20:26:18][INFO] : [Bibliothèque][Volet Auto][Gestion Manuel] : Un evenement manuel a été détecté: La gestion a été désactivée

Je pense que ce genre d'erreur se produit lorsqu'un même objet est utilisé dans plusieurs Evenements, sur le même volet.
Ici j'utilise le MODE de l'appartement (Alive, Sleep, Empty, Hibernate, Manual) pour agir sur les volets : 
Empty Ete -> Volet à 25% 
Empty Hiver -> Si (35 < [Ratio Horizontal] < 75) Alors Volets à 0% Sinon Volets à 25%
Hibernate -> Volets à 0%

J'essaye d'enlever la gestion Evenement "Hibernate" sur une des pièces et regarde si ça se passe mieux (ce mode n'étant pas souvent utilisé).

Merci pour ce super plugin ! 👍

**Comment by mika-nt28** [comment]
Merci pour le retour.
J'ai constaté egalement chez moi ce probleme mais n'ai pas eu le temps de capturé les log
Je regarde ca
