### ISSUE TITLE
Affichage bizarre sur le dashboard

### ISSUE THREAD

**Issue by smuteau** [mika-nt28/Jeedom-Volets#88]
Mika, je pense qu'il devrait y avoir "Activer" et "Désactiver" sur les 2 premières icônes à la place de "Etat activation" comme sur mon screenshot :
<img width="576" alt="capture d ecran 2017-05-30 a 22 14 44" src="https://cloud.githubusercontent.com/assets/16669437/26603012/a122892c-4585-11e7-8f5e-11de806a70b4.png">
Je n'ai pas trouvé où modifier ça dans ton code.

**Comment by mika-nt28** [comment]
En faite cette partie du code est fait pour la V3 qui affichera qu'une seul icone cliquable

**Comment by smuteau** [comment]
ok ça marche, je clos l'issue alors.
