### ISSUE TITLE
Bouton inactif

### ISSUE THREAD

**Issue by jmvedrine** [mika-nt28/Jeedom-Volets#91]
Bonjour Mickael,
Un grand merci pour ce plugin que j'ai découvert récemment quand la saison chaude venant j'en ai eu marre de fermer les volets roulants moi-même pour garder la fraîcheur dans l'appartement.
Hélas il ne fait pas super beau sur Montpellier aujourd'hui donc je me suis dit que j'allais rajouter des conditions pour ne pas fermer les volets en dessous d'une certaine température de la sonde extérieure Netatmo.
Mais depuis la mise à jour de ce matin l'éditeur de conditions a l'air d'avoir un problème : je crée bien la condition mais le bouton Valider (pas le premier celui du choix de la commande, mais le second celui sur l'écran ou on crée la condition avec est égal supérieur, etc) ne fait rien et je viens de me rendre compte que le bouton Ne rien mettre du même dialogue est inactif aussi.
Désolé que mon premier message soit pour signaler un bug mais cela n'enlève rien à l'intérêt de ce plugin.

**Comment by mika-nt28** [comment]
Effectivement avec la derniere modification d'ordenancement des condition j'ai introduit un bug
La correction est fait pour la release de cette nuit
