### ISSUE TITLE
Non vérification des conditions pour l'ouverture et la fermeture jour/nuit

### ISSUE THREAD

**Issue by meichler** [mika-nt28/Jeedom-Volets#93]
Les conditions au lever et au coucher ne sont pas correctement testés s'il y a des filtres.
Il y a une erreur dans ActionNuit et ActionJour.
lors de l'appel : $result=$Volet->EvaluateCondition('open','Day');
Il manque un paramètre il faudrait : $result=$Volet->EvaluateCondition('open','','Day');
Le test des conditions marche alors correctement.

**Comment by mika-nt28** [comment]
Effectivement j'ai oublié cette partie lors des dernière mise a jours
Merci pour ton retour, la correction sera apporté dans la prochaine release
