### ISSUE TITLE
Actions Jour/Nuit exécutées même si désactivé

### ISSUE THREAD

**Issue by meichler** [mika-nt28/Jeedom-Volets#94]
Les actions Jour/Nuit sont exécutées même si elle sont désactivées dans la configuration.
Le cron n'est pas effacé.

**Comment by mika-nt28** [comment]
Effectivement si initialement elles ont ete activé puis desactivé sans stop du demon, les cron ne sont pas effacé.
J'ai corrigé ca pour la prochaine release
