### ISSUE TITLE
Actions d'ouverture et de fermeture différentes pour Position du soleil et Jour / Nuit

### ISSUE THREAD

**Issue by jmvedrine** [mika-nt28/Jeedom-Volets#99]
Bonjour Michael,
Je crois que cela a déjà été demandé sur le forum, mais je ne vois pas d'issue correspondante donc j'en ouvre une
Il serait intéressante que chaque action d'ouverture ou de fermeture ait un menu déroulant avec 
Position du soleil et Jour / Nuit
Position du soleil
Jour /nuit
Jour
Nuit
De cette façon par exemple pour mon cas je pourrait choisir que l'action de fermeture soit de fermer ou ouvrir certains volets mais en laissant un léger jour en bas si c'est une action pour position du soleil et de les fermer complètement si c'est le coucher du soleil ou de les ouvrir complètement si c'est le lever du soleil.
Pour le moment je m'en tire avec des virtuels et des scénarios mais comme j'ai 5 zones c'est pas de la tarte.
Ceci dit ce n'est pas essentiel, et peut-être que peu d'utilisateurs seraient intéressés ?

**Comment by mika-nt28** [comment]
J'ai repris les même éléments que les conditions pour offrir encore plus de possibilité.
La beta etant modifié pour le V3, cette demande sera donc dans la prochaine release du plugin en V3

**Comment by jmvedrine** [comment]
Super. Merci pour tout le travail. Tu peux fermer cette issue.
